matchmaker/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^question/', include('questions.urls')),
    url(r'^', include('newsletter.urls')),
   ]

newsletter/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
]

questions/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
	url(r'^$', views.home, name='question_home'),
	url(r'^(?P<id>\d+)/$', views.single, name='question_single'),

]

newsletter/models.py
from django.db import models

class SignUp (models.Model):
	email = models.EmailField()
	full_name = models.CharField(max_length=120, blank=True, null=True)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __str__(self):
		return self.email

questions/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
	text = models.TextField()
	active = models.BooleanField(default=True)
	draft = models.BooleanField(default=False)
	timestamp = models.DateTimeField(auto_now_add=True,auto_now=False)
	#answers = models.ManyToManyField('Answer')
	def __unicode__(self):
		return self.text[:10]


class Answer(models.Model):
	question = models.ForeignKey(Question)
	text = models.CharField(max_length=120)
	active = models.BooleanField(default=True)
	draft = models.BooleanField(default=False)
	timestamp = models.DateTimeField(auto_now_add=True,auto_now=False)

	def __unicode__(self):
		return self.text[:10]

newsletter/forms.py
from django import forms

from .models import SignUp

class ContactForm(forms.Form):
	full_name = forms.CharField()
	email = forms.EmailField()
	message = forms.CharField()

class SignUpForm(forms.ModelForm):
	class Meta:
		model = SignUp
		fields = ['full_name','email']

	'''def clean_email(self):
		email = self.cleaned_data.get('email')
		email_base, provider = email.split("@")
		domain,extension = provider.split('.')
		if not domain == 'USC':
			raise forms.ValidationError("Plz make sure you use your usc email")
		if not extension == "edu":
			raise forms.ValidationError("plz use a .EDU valid email")
		return email'''

	def clean_full_name(self):
		full_name = self.cleaned_data.get('full_name')
		return full_name	

questions/forms.py
from django import forms

class UserResponseForm(forms.Form):
	question_id = forms.IntegerField()
	answer_id = forms.IntegerField()
	

newsletter/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render

from questions.models import Question
from .forms import ContactForm, SignUpForm
from .models import SignUp


def home(request):
    title = 'Welcome'
    form = SignUpForm(request.POST or None)
    context = {
        "title":  title,
        "form":form,
    }
    if form.is_valid():
        #form.save()
        instance = form.save(commit=False)
        if not instance.full_name:
            instance.full_name = "Unknown"
        instance.save()
        context = {
            "title": "Thank You"
        }
    return render(request,"home.html", context)


def contact(request):
    form = ContactForm(request.POST or None)
    title = 'Contact us'
    context = {"form":form,
               "title":title,
    }
    if form.is_valid():
        email = form.cleaned_data.get("email")
        from_message = form.cleaned_data.get("message")
        from_full_name = form.cleaned_data.get("full_name")
        subject = 'Site contact form'
        from_email = settings.EMAIL_HOST_USER
        to_email = [from_email]
        contact_message = "%s: %s via %s"%(
            from_full_name,
            from_message,
            email)

        send_mail(subject,
            contact_message,
             from_email,
             to_email,
             fail_silently=True)

    return render(request,"forms.html",context)

def about(request):
    return render(request, "about.html")

questions/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect

from .models import Question
from .forms import UserResponseForm

def single(request, id):
    if request.user.is_authenticated():
    	form = UserResponseForm(request.POST or None)

    	if form.is_valid():
            question_id = form.cleaned_data.get('question_id')
            answer_id = form.cleaned_data.get('answer_id')
            question_instance = Question.objects.get(id=question_id)
            answer_instance = Answer.objects.get(id=answer_id)
            next_q = Question.objects.all().order_by("?").first()
            return redirect("question_single", id=next_q.id)


        queryset = Question.objects.all().order_by('-timestamp')
        instance = get_object_or_404(Question, id=id)

        context={
        	"form":form,
        	"instance":instance,
            #"qweryset":qweryset,
        }
        return render(request,"questions/home.html", context)	
    else:
    	raise Http404

def home(request):
    if request.user.is_authenticated():

    	form = UserResponseForm(request.POST or None)
    	if form.is_valid():
    		print form.cleaned_data

        queryset = Question.objects.all().order_by("-timestamp")
        instance = queryset[1]
        context={
        	"form":form,
        	"instance":instance,
            #"qweryset":qweryset,
        }
        return render(request,"questions/home.html", context)	
    else:
    	raise Http404

newsletter/templates/about.html
{% extends 'base.html' %}


{% block content %}
    <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
        <h1>About us</h1>
        <p>Marriage, also called matrimony or wedlock, is a socially or ritually recognized union or legal contract between spouses that establishes rights and obligations between them,\
            between them and their children, and between them and their in-laws.[1] The definition of marriage varies according to different cultures, but it is principally
            an institution in which interpersonal relationships,
            usually sexual, are acknowledged. In some cultures
            , marriage is recommended or considered to be compulsory before pursuing any sexual activity. When defined broadly, marriage is considered a cultural universal.</p>
    </div>
    </div>
{% endblock %}

newsletter/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>Matchmaker</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" 
     rel="stylesheet">

    <link href="{% static 'css/navbar-static-top.css' %}" rel="stylesheet">
    <link href="{% static 'css/coustom.css' %}" rel="stylesheet">

    <script src="../../assets/js/ie8-responsive-file-warning.js"></script>
    <script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>


      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  </head>

<style>
{% block style %}


{% endblock %}

</style>

  <body>


  {% include 'navbar.html' %}
  {% block jumbotron %}
  {% endblock %}
  <div class="container">


    	{% block content %}
    	{% endblock %}


 	</div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{% static 'js/vendor/jquery.min.js' %}"><\/script>')</script>
    <script src"{% static 'js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
  </body>
</html>

newsletter/templates/forms.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<div class="row">
    <div class="col-sm-6 col-sm-offset-3" >
        <h1 style="text-align: center;"><strong>{{ title }}</strong></h1>
        <form method='POST' action=''>
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" name="" value='Submit'>
        </form>
    </div>
</div>
{% endblock %}

newsletter/templates/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

<style>
{% block style %}
.navbar-static-top {
  margin-bottom: 0px !important;
}
body {
  min-height: 1000px;
}

{% endblock %}

</style>


{% block jumbotron %}
{% if  not request.user.is_authenticated %}

<div class="jumbotron" style="background-color:green; color:#f9f9f9;">
    <div class="container">
    <div class="row">
        <div class="col-sm-6">
            <h1>Matchmaker</h1>
            <p>This example is a quick exercise to illustrate how the default, static and fixed to top 		navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport 	and device.
            </p>
            <p>To see the difference between static and fixed top navbars, just scroll.</p>
            <p><a class="btn btn-lg btn-primary" href="/contact/" role="button">Contact us &raquo;</a></p>
        </div>
        <div class="col-sm-6" style=" black;height: 315px;">
            <iframe width="600" height="315" src="https://www.youtube.com/embed/nFzdfqEH-7E" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>
    </div>
{% endif %}
</div>

{% endblock %}


{% block content %}

<!--{% if  request.user.is_authenticated %}
      <h1>You are logged in!</h1>
    {% if qweryset %}
        <h1>Welcome Staff</h1>
        <table class="table">
        {%  for i in qweryset %}
            <tr><td>{{ forloop.counter }}</td><td>{{ i }}</td><td>{{ i.full_name }}</td><td>{{ i.timestamp| timesince }}</td></tr>
        {% endfor %}
        </table>
     {% endif %}
{% else %}-->

<div class="row">
    <div class="col-sm-3  pull-right" >
        <p class="lead"><strong>{{ title }}</strong>


        <form method='POST' action=''>
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-primary" type="submit" name="" value='SignUp'>
        </form>

    </div>
    <div class="col-sm-3" >
        <p class="lead text-align-center">Built with django </p>
    </div>
    <div class="col-sm-3" >
        <p class="lead">Matchmaker</p>
    </div>
    <div class="col-sm-3" >
        <p class="lead">Open source project</p>
    </div>
</div>
{% endif %}
{% endblock %}

newsletter/templates/navbar.html
{% load staticfiles %}
    <nav class="navbar navbar-default navbar-static-top" style="background-color: black;">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand"  href="/"><img src="{% static 'img/logo.png' %}" /></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav" style="color:white;">
            <li ><a href="/">Home</a></li>
            <li><a href="/about/">About</a></li>
            <li><a href="/contact/">Contact</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
            <li><a href="/accounts/logout/">logout</a></li>
            {% else %}
                <li><a href="/accounts/register/">Register</a></li>
            {% endif %}
          </ul>

            {% if not request.user.is_authenticated %}
            <form class="navbar-form navbar-right" method="post" action="{% url 'auth_login' %}">{% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" name="username" placeholder="Username">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="password" placeholder="Password">
                </div>
                <button type="submit" class="btn btn-default">Login</button>
            </form>
            {% endif %}
        </div><!--/.nav-collapse -->
      </div>
    </nav>

newsletter/templates/questions/home.html
{% extends 'base.html' %}


{% block content %}

<form method="POST" action=""> {% csrf_token %}
<h1>{{ instance.text }}</h1>
	<input type="hidden" name="question id" value='{{ instance.id }}'/>
{% for ans in instance.answer_set.all %}
<input type='radio' name='answer_id' value='{{ ans.id }}'/> {{ ans.text }} <br/>
{% endfor %}

<input class="btn btn-primary" type="submit" value="save and continue"/>
</form>


{% endblock %}